name: "Backend Tests"

on:
  - "push"
  - "pull_request"

jobs:
  backend:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        php-versions: ['7.3']

    steps:
      - uses: "actions/checkout@v2.0.0"
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "composer-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}"
          restore-keys: "composer-${{ matrix.php-version }}-"

      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "intl, xdebug, imagick, apcu"
      - name: "Install SSH key"
        uses: "shimataro/ssh-key-action@v2"
        with:
          key: "${{ secrets.SSH_KEY_CI }}"
          name: "id_rsa"
          known_hosts: "${{ secrets.SSH_KNOWN_HOST_AKENEO_EE }}"

      # Install / Prepare
      - name: "Add EE Composer repository"
        run: "composer -n config repositories.ee vcs ${{ secrets.SSH_AKENEO_EE_REPOSITORY }}"
      - name: "Install PHP dependencies"
        run: "composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

      # CI
      - name: "PHPSpec"
        run: "vendor/bin/phpspec run"
      - name: "Integration tests"
        run: "vendor/bin/phpunit"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpspec-${{ matrix.php-versions }}.coverage"
          path: "build/coverage.xml"

  coverage-upload:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-18.04"

    needs:
      - "backend"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: "reports"
          flags: "backend"
