name: "Frontend Code Analysis + Style"

on:
  - "push"
  - "pull_request"

jobs:
  frontend:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        php-versions: [ '7.4' ]

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "intl, xdebug, imagick, apcu"
      - name: "Install SSH key"
        uses: "shimataro/ssh-key-action@v2"
        with:
          key: "${{ secrets.SSH_KEY_CI }}"
          name: "id_rsa"
          known_hosts: "${{ secrets.SSH_KNOWN_HOST_AKENEO_EE }}"

      # Install / Prepare
      - name: "Add EE Composer repository"
        run: "composer -n config repositories.ee vcs ${{ secrets.SSH_AKENEO_EE_REPOSITORY }}"
      - name: "Install PHP dependencies"
        run: "composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

      - name: "yarn install"
        uses: "borales/actions-yarn@v2.0.0"
        with:
          cmd: "install"

      - name: "Check for obsolete ts exports"
        run: "yarn ts-unused-exports tsconfig.json $(find src/Resources/public -name '*.ts*') --showLineNumber"

      - name: "Typescript linting"
        run: "yarn tslint src/Resources/public/**/*.ts src/Resources/public/**/*.tsx src/Resources/public/**/**/*.tsx"

      - name: "Coding Style"
        run: "yarn prettier --config .prettierrc.json --check src/Resources/public/**/*.ts src/Resources/public/**/*.tsx jest/**/*.ts jest/**/*.tsx"
